# comment or uncomment lines to use the window manager or 
# desktop environment of your choice.

# gnome2
#/usr/local/bin/gnome-session

# xfce4
#/usr/local/bin/startxfce4

# use awesome in xfce4
#sleep 100 
# open your theme
#xfce-settings-show &
# open network manager
#run-applet &
#exec /usr/local/bin/awesome


# dwm
/usr/local/bin/dwm
#feh --bg-scale /home/assess0r/img/bg.jpg
#while true
#do
#	xsetroot -name "$(date +'%a %b %d %r')"
#	sleep 1s
#done & exec /usr/local/bin/dwm

# awesome-wm
#/usr/local/bin/awesome
